#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=11

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
cd "$(dirname "$SCRIPT_DIR")"

banner "Fikk Mobile ESP32 BLE validation"

stage "PlatformIO and board connection"
say "Connect the confirmed ESP32 DevKit V1 with a USB data cable. Do not infer the chip/module or hardware revision from the board name."
step "From the repository root, verify PlatformIO is available: python -m pip install platformio"
step "Run: pio device list"
step "Confirm a serial port appears for the connected ESP32 board. If no port appears, fix the USB cable/driver before continuing."
pause "When the board serial port is visible, press Enter"

stage "Select the serial port"
say "The port is transient and is not written to .env or any secret store."
ask UPLOAD_PORT "Enter the ESP32 serial port (for example COM5):"
if [[ -z "$UPLOAD_PORT" ]]; then
  warn "No serial port entered; stop and rerun after connecting the board."
  exit 1
fi
note "Using serial port $UPLOAD_PORT for this run only."
pause "Confirm the port is correct, then press Enter"

stage "Flash the firmware"
say "This overwrites the firmware on the selected board."
step "The exact command is: pio run -d firmware -e esp32dev -t upload --upload-port $UPLOAD_PORT"
if ! confirm "Flash firmware to $UPLOAD_PORT now?"; then
  warn "Firmware flash skipped."
  exit 1
fi
pio run -d firmware -e esp32dev -t upload --upload-port "$UPLOAD_PORT"
pause "After PlatformIO reports a successful upload, press Enter"

stage "Confirm boot and advertising"
say "Open a second terminal so this wizard remains available."
step "Run: pio device monitor -d firmware -e esp32dev --port $UPLOAD_PORT"
step "Confirm the serial output contains BOOT, BLE_INIT, and BLE_ADVERTISING."
step "The expected local name is Fikk-ESP32 and the advertised service UUID is c8c5aefd-0e30-525e-9bf9-5243913c8127."
step "Stop the monitor with Ctrl-C after capturing the boot/advertising lines."
pause "After capturing the serial evidence, press Enter"

stage "Build the mobile custom development client"
say "The current Fikk Mobile app shell does not yet expose the Settings scan UI. Build it for later integration, but use a BLE inspector for this low-level validation."
step "On a machine with the Android SDK and a physical Android phone, run: pnpm exec expo run:android --device"
step "Install the resulting custom development build on the phone. Do not use Expo Go for BLE validation."
step "Keep the phone and flashed ESP32 available for the next stages."
pause "When the custom development build is installed, press Enter"

stage "Scan, connect, and discover GATT"
open_url "https://www.nordicsemi.com/Products/Development-tools/nrf-connect-for-mobile"
say "Use nRF Connect for Mobile or another BLE inspector that can scan, connect, discover, read, write, and subscribe."
step "Scan for Fikk-ESP32 and confirm the advertised service UUID."
step "Connect and discover the custom service."
step "Confirm these characteristics: CONTROL c42f890d-088a-5b19-bcd4-5029fceb2bcc; EVENT 57a6c81b-268e-5eed-995b-2149521b911f; STATE 8271b32c-fa20-5adc-a4d0-141bf24baa71; DEVICE_INFO 98ef338e-f5f8-5ea4-b89f-116d303090a3."
pause "After all four characteristics are visible, press Enter"

stage "Read and subscribe"
say "Validate characteristic properties before sending commands."
step "Read DEVICE_INFO. Expected text includes firmware=0.1.0, protocol=1, board=ESP32 DevKit V1, chip=unknown, and hardware_revision=unknown."
step "Read STATE and decode the protocol v1 packet. Initial state should be READY (state value 0) with session ID 0."
step "Subscribe to EVENT and STATE notifications."
step "Capture the characteristic properties and initial packets for the questionnaire."
pause "After reads and subscriptions are confirmed, press Enter"

stage "Exercise START, simulation, and STOP"
say "Use the BLE inspector's hex write-with-response action on CONTROL. DEV SIMULATION is enabled; no GPIO or sensor wiring is assumed."
step "Send START with session ID 0x01020304, sequence 0, target count 6: 01 01 04 03 02 01 00 00 06"
step "Confirm an ACK with command 0x01 and status 0, followed by ACTIVE STATE (state value 1)."
step "Wait for DEV SIMULATION. Confirm PROGRESS notifications arrive about every 2 seconds with increasing counts."
step "Before count 6 if you want to test STOP, send STOP with the same session ID, sequence 0, user reason 1: 01 02 04 03 02 01 00 00 01"
step "Confirm accepted STOP ACK, COMPLETE with STOPPED reason 2, and COMPLETED STATE (state value 2). If STOP is not sent, confirm COMPLETE at count 6 with TARGET_REACHED reason 1."
pause "After START and the chosen completion path are captured, press Enter"

stage "Exercise disconnect, reconnect, and SYNC"
say "Disconnect must not destroy the logical session."
step "Disconnect the BLE inspector while the session is ACTIVE or after COMPLETE. Confirm the ESP serial log shows BLE_DISCONNECTED and BLE_ADVERTISING."
step "Reconnect and rediscover the service/characteristics."
step "Send SYNC for the session: version 1, type 0x03, the retained session ID in little-endian, sequence 0, no payload."
step "Confirm accepted SYNC ACK and STATE. For a completed session, confirm COMPLETE is replayed with the retained result sequence."
pause "After reconnect and recovery are confirmed, press Enter"

stage "Acknowledge the result"
say "Only acknowledge a completed result after recording its COMPLETE packet."
step "Read the result sequence from COMPLETE. Encode it as a little-endian uint16 payload."
step "Send ACK_RESULT with the same session ID and the captured result sequence."
step "Confirm accepted ACK_RESULT ACK, READY STATE, session ID 0, and cleared retained result."
step "If the sequence is wrong, confirm the firmware rejects it and retains the result; do not clear it by guessing."
pause "After ACK_RESULT behavior is captured, press Enter"

stage "Record verified hardware facts and update the questionnaire"
say "Only record values physically verified from the board, SDK output, or firmware evidence."
ask CHIP_MODULE "Enter the exact ESP chip/module only if physically verified (leave blank otherwise):"
ask HARDWARE_REVISION "Enter the hardware revision only if physically verified (leave blank otherwise):"
note "Exact ESP chip/module: ${CHIP_MODULE:-unknown/unverified}"
note "Hardware revision: ${HARDWARE_REVISION:-unknown/unverified}"
step "Update to-questionnaire-esp-ble.md with the captured firmware, UUID, GATT, packet, advertising, and physical-validation evidence."
step "Keep the exact chip/module and hardware revision blank unless the values above were independently verified."
step "Attach serial logs and BLE captures where the questionnaire asks for them."
pause "After the questionnaire and evidence are updated, press Enter"

finish
